version: '3'

services:
  wordee:
    restart: always
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - BOT_TOKEN=YOUR_BOT_TOKEN
      - DB_HOST=db
      - DB_USER=DB_USER
      - DB_PASSWORD=DB_
      - DB_NAME=DB_NAME
      - DB_SSLMODE=DB_SSLMODE
      - DB_PORT=5432
    command: bash -c "goose -dir internal/migrations postgres 'host=db port=5432 user=DB_USER password=DB_PASSWORD dbname=DB_NAME sslmode=DB_SSLMODE' up && ./wordee"

  db:
    restart: always
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_USER=DB_USER
      - POSTGRES_DB=DB_NAME
    ports:
      - "5436:5432"