version: '3.8'

services:
  wordee:
    restart: always
    build: ./
    command: ./wordee
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - BOT_TOKEN=YOUR_TOKEN
      - DB_HOST=db
      - DB_USER=USER
      - DB_PASSWORD=PASSWORD
      - DB_NAME=DB_NAME
      - DB_SSLMODE=disable
      - DB_PORT=5432

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=PASSWORD
      - POSTGRES_USER=USER
      - POSTGRES_DB=DB_NAME
    ports:
      - "5436:5432"